import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
//import Providers from "./providers/page";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Qflows",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <link rel="icon" href="/qflowslogo.png" type="image/Qflows-icon" /> */}
      <head>
        {/* <script
          async
          src="https://cdn.jsdelivr.net/pyodide/v0.21.3/full/pyodide.js"
        ></script> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Providers>{children}</Providers> */}
        {children}
      </body>
    </html>
  );
}
